version: '3.8'  # Version de Compose, puedes usar la más reciente compatible

services:
  postgres:
    image: postgres:latest  # Usa la última imagen oficial de PostgreSQL
    restart: unless-stopped
    container_name: spaceships-container  # Nombre del contenedor
    environment:
      POSTGRES_DB: spaceships  # Nombre de la base de datos
      POSTGRES_USER: admin    # Usuario de la base de datos
      POSTGRES_PASSWORD: myapptest123  # Contraseña del usuario
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del contenedor al puerto 5432 de la máquina local
#    volumes:
#      - pgdata:/var/lib/postgresql/data  # Define un volumen para la persistencia de datos
#    networks:
#      - mi_red

# Define el volumen para la persistencia de datos
# volumes:
#  pgdata:

# Define una red para los servicios
# networks:
# mi_red:
